language: node_js
node_js:
  - "node"
before_install:
  - export NG_CLI_ANALYTICS=ci
script:
  -
branches:
  only:
    - master
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "lRqm4gQqChUfmfp1+izbOyYPZTAc3lqVzbSaSXg+qTxKzszMD/3Z4yxozWCh7oXuDdn7rJtVQvHH3Oq66t/AzQFpxYD0p+MkyX/WfSUpZAw9lHVovVUHPk41K+BxE7zI5eJza5rPU9ZvcE3nH3QDMqEm12Xewixv94lNB9pBbToW0tffhZouHMKwzmQTpTnOK1dHRMDO13I/wRH2Rw5sGFZKsImAu8OvzkK/hY/kV94LQDAjKB2RbPqMIRhnut3sVP26QgksNqLcA5nkvkZpjLWXEfYb0rNujXR4jo2TXv0+T5ZDjUkUz/cBHI9OHtY8/8UDfArZ8n+etdNauL1RF61QhGjkYFfniDP6xINuD39KblQTcpa+xWnANGPlJ/wA8BdtLuilUe75TNOsXOI3rPjc5Rhevo8aAQBpaCi5TGVO36M4qSYN6U01UlCo/CVlg200iD3dUvmORlK94bmY7xpo4GClhvs0wzovHcOx3SfAQU/42giNwueDlUTp9UKffG+B8KS/rZ6o2EICIX124b1nCZMQaHOPup1qYUM8hrTsQqXs5pFiywFUUNpFRb+8aNpZbw7hy4Je4DfgiKNamZeqLjFARSop9mvZJLJEZfaqlWwWEkQu/OCjojeoz50dgMnPp6MVJx5jugwAYHTweV5GfXopTlL+/fJDWTPilPs="
"
